### PR TITLE
Copy all TaskRunner related classes from 'Command Task Runner'

### PR DESCRIPTION
**Pull request by sboulema**
- Copy all TaskRunner related classes from 'Command Task Runner'
- Replace commands.json with tasks.vs.json
- Replace CommandTask class with new structure

ps. Really wanted to test the new GitHub 'Draft Pull Request' 😄

### CODE REVIEW

**Comment by uilianries** [comment]
> ps. Really wanted to test the new GitHub 'Draft Pull Request' smile

Gitlab allows to use `WIP` in MR title. Much better IMO.

**Comment by solvingj** [comment]
i think we're good to merge this for now.

**Comment by solvingj** [comment]
i guess we can't merge it until @sboulema changes from draft.

**Comment by sboulema** [comment]
Will continue with this tomorrow! Haven't even locally tested this yet...

**Pull request merged**
