### PR TITLE
Dump fixes

### PR DESCRIPTION
**Pull request by SSE4**
several stupid fixes to get button working with no exceptions

### CODE REVIEW

**Comment by chriscoy82** [comment]
Yeah, looks like that works on my machine now. I did read that we may need
additional trickery to get this to support multiple versions of Visual
Studio... which I'm not excited to test, but at least this gets us past
that hurdle and we can keep working to make this happen.
I'll try to work on this some this week.
Thanks!

**Comment by solvingj** [comment]
I’m not very interested in pre-2015. Even 2017+ would be acceptable. Keeping in mind that this is not about msvc compiler version but actual GUI UX and workflow. And, since the extension is only relevant to projects which are “allowed to use conan”, Potentially a majority of these will be forward-thinking projects which has devs using 2017 already. Obviously not all.

**Comment by SSE4** [comment]
if some pre-2015 testing is needed, I have all versions of Visual Studio from 2005 to 2017 installed and can test. but probably it makes sense to do later, once everything works well on 2017.

**Comment by chriscoy82** [comment]
yeah, perhaps just 2015 & 2017 would be fine.

**Pull request merged**
